import Head from "next/head";
import { useRouter } from "next/dist/client/router";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
	const router = useRouter();
	const [username, setUsername] = useState("");

	useEffect(() => {
		const getCookieValue = (name) =>
			document.cookie.match("(^|;)\\s*" + name + "\\s*=\\s*([^;]+)")?.pop() ||
			"";
		const token = getCookieValue("token");
		fetch("/api/auth", {
			method: "POST",
			headers: {
				"content-type": "application/json",
			},
			body: JSON.stringify({ token }),
		})
			.then((d) => d.json())
			.then((data) => {
				if (data.message === "not ok") {
					return router.push("/login");
				}
				setUsername(data.data.username);
			})
			.catch((err) => console.error(err));
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Simple Auth - HOME</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Hello {username}</h1>
			</main>
		</div>
	);
}
