import styles from "../styles/Login.module.css";
import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/dist/client/router";

const register = () => {
	const [username, setUsername] = useState("");
	const [password, setPassword] = useState("");
	const router = useRouter();

	const handleSubmit = (e) => {
		e.preventDefault();
		if (!username || !password)
			return alert("please fill the details properly");

		const data = { username, password };
		fetch("/api/register", {
			method: "POST",
			headers: {
				"content-type": "application/json",
			},
			body: JSON.stringify(data),
		})
			.then((t) => t.json())
			.then(({ user }) => {
				alert(
					`Welcome ${user.username}, your account has been created successfully.`
				);
				router.push("/login");
			})
			.catch((err) => console.error(err));
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Simple Auth - Register</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<form className={styles.form} onSubmit={handleSubmit}>
				<h2>Register</h2>
				<input
					type="text"
					name="username"
					placeholder="Username"
					value={username}
					onChange={(e) => setUsername(e.target.value)}
				/>
				<input
					type="password"
					name="username"
					placeholder="Password"
					value={password}
					onChange={(e) => setPassword(e.target.value)}
				/>
				<button>Register</button>
			</form>
		</div>
	);
};

export default register;
